name: Email Step Test

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3001825@ds.study.iitm.ac.in
        run: echo "Hello, world!"
